### ISSUE TITLE
Latest jupyter version breaks CI

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#151]
```
ERROR: test_plot_forecast_jupyter (tests.test_forecast_plot.TestForecastPlot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_forecast_plot.py", line 190, in test_plot_forecast_jupyter
    auto_open=False)
  File "anticipy/forecast_plot.py", line 467, in plot_forecast
    return py.offline.iplot(fig, show_link=False)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/plotly/offline/offline.py", line 398, in iplot
    animation_opts=animation_opts,
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/plotly/io/_renderers.py", line 385, in show
    "Mime type rendering requires nbformat>=4.2.0 but it is not installed"
ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed
```

This was while rerunning a previously successful test, so purely a library version issue.

**Comment by capelastegui** [comment]
We need to add the following libraries to setup.py:

pip install "notebook>=5.3" "ipywidgets==7.5"
