### ISSUE TITLE
Naive model - Length of passed values is 100, index implies 88.

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#199]
```
======================================================================
ERROR: test_run_forecast_naive2 (tests.test_forecast.TestForecast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sky-uk/anticipy/tests/test_forecast.py", line 1873, in test_run_forecast_naive2
    season_add_mult='add')
  File "/home/travis/build/sky-uk/anticipy/anticipy/forecast.py", line 946, in run_forecast
    use_cache=use_cache
  File "/home/travis/build/sky-uk/anticipy/anticipy/forecast.py", line 1373, in run_forecast_single
    df_actuals=df_actuals_interpolated)
  File "/home/travis/build/sky-uk/anticipy/anticipy/forecast.py", line 728, in extrapolate_model
    s_y_forecast = pd.Series(data=a_y_forecast, index=s_x.index, name='y')
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas/core/series.py", line 314, in __init__
    f"Length of passed values is {len(data)}, "
ValueError: Length of passed values is 100, index implies 88.
```

**Comment by capelastegui** [comment]
Caused by #198 - need to integrate change with extrapolate_model(), get_s_x_extrapolate()
