### ISSUE TITLE
Install from pypi broken in python 3

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#92]
`pip install anticipy` crashes when using python 3:

``` 
Collecting anticipy
  Using cached https://files.pythonhosted.org/packages/0d/13/26dd6dfd41aac2ca5496ec1138228db4174f5cf7e295651fed79f7c2bc00/anticipy-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sr/1xjp59_n7f9gsdhm_xklrff1707p6r/T/pip-install-wm8mu00w/anticipy/setup.py", line 30, in <module>
        with open("pypi-description.rst", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'pypi-description.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sr/1xjp59_n7f9gsdhm_xklrff1707p6r/T/pip-install-wm8mu00w/anticipy/
```

This works fine on python 2. Also, installing from a cloned git repo (as we do in travis CI) works fine for both versions.

**Comment by capelastegui** [comment]
The only way to test a fix is to push a new release to test.pypi.org, and trying to install from there. 

Potential reasons for the error:
- dist and wheel files created from python 2
- Outdated versions of setuptools, pip. Last release was created with setuptools 40.4.3, pip 9.0.1.

**Comment by ibegleris** [comment]
#93
